apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: sravan1327/payment-service:latest
          ports:
            - containerPort: 4004
          env:
            - name: PORT
              value: "4004"
            - name: MONGO_URL
              value: "mongodb+srv://ussravanu:YmhSrOELQRuV74cU@cluster0.r6tnwaq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - port: 4004
      targetPort: 4004
      nodePort: 30004
