apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sravan1327/product-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
            - name: MONGO_URL
              value: "mongodb+srv://ussravanu:B9Nxyvzpon2S6UKF@cluster0.u73skvt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - port: 4001
      targetPort: 4001
      nodePort: 30001
